-- OPS-004 bootstrap. Applied by a human (RULE-09), never by an agent.
--
-- This is the PRODUCTION bootstrap and it is not supabase/seed.sql. It contains no password, token
-- or key of any kind, and it creates no auth user: it resolves a person who has ALREADY SIGNED UP
-- through the shipped interface, and gives that person the first team and the first admin member
-- row. That is the whole difference from seed.sql, and it is why this file may be pointed at a real
-- project while that one may not (ADR-024, ADR-030).
--
-- THE SEQUENCE THIS FILE SERVES. Admin zero signs up through the application and lands on the
-- member-less screen, which is correct behaviour and not a fault (ADR-009; src/routes/NotOnATeam.tsx).
-- A human then applies this file once. That admin allow-lists everybody else, and the ordinary
-- sign-up flow runs from there for every person after them.
--
-- BEFORE THE FIRST APPLICATION TO ANY PROJECT, RUN THESE TWO READ-ONLY QUERIES AND READ THE ANSWERS.
-- Nothing in this repository can tell you what a hosted project already contains — ADR-024 declined a
-- drift detector — so this listing is an obligation and not a suggestion. It is exactly what the
-- refusals below test, so A SURPRISING ANSWER TO EITHER ONE MEANS STOP RATHER THAN ADJUST:
--
--   select id, name from public.team;
--   select id, role, removed_at from public.member;
--
-- HOW TO APPLY IT — Supabase dashboard, SQL editor, as ONE submission. Replace the placeholder with
-- the address admin zero signed up with; the team name is yours to choose:
--
--   set calechip.bootstrap_email     = 'admin-zero@example.com';
--   set calechip.bootstrap_team_name = 'CaleChip';
--   -- ...then paste everything below this header into the same submission and run it together.
--
-- OR, when SUPABASE_DB_URL is to hand:
--
--   PGOPTIONS="-c calechip.bootstrap_email=admin-zero@example.com -c calechip.bootstrap_team_name=CaleChip" psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 --single-transaction -f supabase/bootstrap.sql
--
-- DO NOT EDIT THIS FILE IN ORDER TO RUN IT. The address is supplied at the connection and never
-- committed: an edited-but-uncommitted SQL file is precisely the drift ADR-024 exists about, and a
-- real person's address does not belong in this repository (ADR-030 decision point 4).
--
-- It is ONE statement — a single `do $$ ... $$;` block — so it is atomic without a begin/commit that
-- the dashboard editor would fight, and every refusal below leaves the database exactly as it was.
-- It carries no psql meta-command, so the editor, which is not psql, accepts it verbatim
-- (supabase/seed.sql:31-32 is the precedent).
--
-- `display_name` and `avatar` below are a DELIBERATE COPY of the derivation the sign-up trigger uses
-- at 20260831150024_tea01_membership.sql:113-117, so that admin zero's row looks like every row the
-- trigger writes; two derivations of the same two columns that disagreed would be a second source.

do $$
declare
  -- Both settings are read through the same wrapper. `current_setting(..., true)` returns NULL
  -- rather than raising when the name is unset — the mechanism supabase/seed.sql:39 already uses —
  -- and the btrim/nullif pair is what makes a whitespace-only value refuse here instead of reaching
  -- `name text not null` as a blank team name.
  v_email_setting text :=
    nullif(btrim(coalesce(current_setting('calechip.bootstrap_email', true), '')), '');
  v_team_name text :=
    nullif(btrim(coalesce(current_setting('calechip.bootstrap_team_name', true), '')), '');

  v_listing constant text :=
    'Read the project before acting on it: `select id, name from public.team;` and '
    || '`select id, role, removed_at from public.member;`. A surprising answer means stop rather '
    || 'than adjust.';
  v_invocations constant text :=
    'Supply both settings at the connection, never by editing this file. Dashboard SQL editor, as '
    || 'one submission: set calechip.bootstrap_email = ''<the address admin zero signed up with>''; '
    || 'set calechip.bootstrap_team_name = ''<your team name>''; then paste this file below them. '
    || 'Or, with SUPABASE_DB_URL to hand: PGOPTIONS="-c calechip.bootstrap_email=... '
    || '-c calechip.bootstrap_team_name=..." psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 '
    || '--single-transaction -f supabase/bootstrap.sql';

  v_match_count integer;
  v_team_count  integer;
  v_admin_count integer;

  v_uid        uuid;
  v_email      text;
  v_meta       jsonb;
  v_team_id    uuid;
  v_role       public.member_role;
  v_removed_at timestamptz;
begin
  -- AC-1. Either setting missing or blank refuses, and the hint names both invocations.
  if v_email_setting is null then
    raise exception
      'bootstrap.sql refused to run: calechip.bootstrap_email is unset, empty or whitespace-only'
      using hint = v_invocations || ' ' || v_listing;
  end if;

  if v_team_name is null then
    raise exception
      'bootstrap.sql refused to run: calechip.bootstrap_team_name is unset, empty or whitespace-only'
      using hint = v_invocations || ' ' || v_listing;
  end if;

  -- AC-2 and AC-3. The address is matched case- and whitespace-insensitively, because the operator
  -- types it by hand into a dashboard field and a capitalised first letter returning "no auth user"
  -- would send them looking for a sign-up that already happened. That widens ADR-030 decision
  -- point 5's `email = current_setting(...)` predicate, and widening it weakens the ADR's argument
  -- that GoTrue's unique index makes a second match impossible — so THIS FILE COUNTS RATHER THAN
  -- ASSUMING, which is what the ADR says it does in the same sentence (01-plan.md section 4).
  select count(*) into v_match_count
    from auth.users u
   where lower(btrim(u.email)) = lower(v_email_setting);

  if v_match_count = 0 then
    raise exception 'no auth user with that address; sign up through the application first'
      using hint = v_listing;
  end if;

  if v_match_count > 1 then
    raise exception
      'bootstrap.sql refused to run: % auth users match that address, expected exactly one',
      v_match_count
      using hint = v_listing;
  end if;

  select u.id, u.email, u.raw_user_meta_data
    into v_uid, v_email, v_meta
    from auth.users u
   where lower(btrim(u.email)) = lower(v_email_setting);

  -- AC-6. v1 is single-team (.ai/00-charter.md:30; multiple teams are deferred to P2 at :64-66), and
  -- a project holding two is a state this file must not act inside. Counted here, before any write
  -- is decided, so the count is available to the reuse branch below without a second query.
  select count(*) into v_team_count from public.team;

  if v_team_count > 1 then
    raise exception
      'bootstrap.sql refused to run: public.team holds % rows, expected zero or one',
      v_team_count
      using hint = v_listing;
  end if;

  -- AC-7, AC-8 and AC-9, evaluated in that order, and the order is the contract (01-plan.md § 4).
  select m.role, m.removed_at
    into v_role, v_removed_at
    from public.member m
   where m.id = v_uid;

  if found then
    -- AC-7. The only silent outcome, and it holds whether or not other active admins exist — it is
    -- evaluated before AC-9 for exactly that reason. Re-applying the file is a no-op, not a repair.
    if v_role = 'admin'::public.member_role and v_removed_at is null then
      raise notice
        'already bootstrapped: public.member already holds an active admin row for that auth user';
      return;
    end if;

    -- AC-8. It never promotes and it never un-removes. Promotion is TEA-04's power and has a
    -- permission row behind it (20260901120000_tea04_member_writes.sql:29, 42-50); a file that
    -- quietly granted admin would be the fail-open shape ADR-030 rejected its Exit C for.
    raise exception 'bootstrap.sql refused to run: public.member already holds a row for that auth user with role = % and removed_at = %; this file never promotes and never un-removes',
      v_role, coalesce(v_removed_at::text, 'null')
      using hint = v_listing;
  end if;

  -- AC-9, and it is the control. No row exists for this uid, so any active admin found here is a
  -- different person: this is the single check standing between the file and a second admin on a
  -- project that already has one.
  select count(*) into v_admin_count
    from public.member m
   where m.role = 'admin'::public.member_role
     and m.removed_at is null;

  if v_admin_count > 0 then
    raise exception 'bootstrap.sql refused to run: this project already has % active admin member row(s) under another id; the bootstrap is for a project that has none',
      v_admin_count
      using hint = v_listing;
  end if;

  -- AC-4 and AC-5. `public.team` has no unique constraint on `name`
  -- (20260831150024_tea01_membership.sql:24-29), so `on conflict do nothing` cannot express "reuse
  -- the one team" — it would insert a SECOND team on the second run and nothing would refuse it.
  -- The count above is the discriminator instead. This is the first write in the file: every
  -- refusal is already behind us.
  if v_team_count = 0 then
    insert into public.team (name)
    values (v_team_name)
    returning id into v_team_id;   -- overload_threshold and created_at take the column defaults
  else
    -- Exactly one row. Reuse it: do not insert, and DO NOT RENAME it to v_team_name.
    select t.id into v_team_id from public.team t;
  end if;

  -- AC-4. `removed_at` stays null and `created_at` takes the column default. `public.allowed_email`
  -- is deliberately untouched: admin zero was never allow-listed, and inventing a consumed row for
  -- them would be a false provenance record in the one table whose purpose is provenance.
  insert into public.member (id, team_id, display_name, avatar, role)
  values (
    v_uid,
    v_team_id,                                    -- INV-07: the team comes from here and nowhere else
    coalesce(nullif(btrim(v_meta ->> 'display_name'), ''),
             split_part(v_email, '@', 1)),        -- copied from ...tea01_membership.sql:113-117
    coalesce(nullif(btrim(v_meta ->> 'avatar'), ''), '🙂'),
    'admin'::public.member_role                   -- the one row in this product that is not written
                                                  -- by the trigger, and the reason this file exists
  );
end
$$;
